
language: node_js
node_js:
  - 10
env:
  - SA_PASSWORD
services:
  - docker
before_script:
  - sudo docker run --name=mssql-server-linux-latest -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=$SA_PASSWORD' -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest
  - sudo docker cp test/docker mssql-server-linux-latest:/tmp/scripts/
  - sudo docker exec -it mssql-server-2017-latest chmod 777 /tmp/scripts/*.sh
  - sudo docker exec -it mssql-server-2017-latest /tmp/scripts/wait-for-it.sh -t 60 localhost:1433
